### ISSUE TITLE
Example ReadMe out of date

### ISSUE THREAD

**Issue by MeaningOfLights** [vivet/Vivet.AspNetCore#13]
Hey, nice library only the documentation is out of date and while its popular googling "site: github.com AddRequestTimeZone" doesn't yield any results.

If you could specify how to wire it up which has changed, I'm not sure why its now an action when it was a TimeZone string?

```
Action<RequestTimeZoneOptions> a = DoWork;
services.AddRequestTimeZone(a); 
```

Also this method is no longer available:

`var local = DateTimeInfo.Local;`

**Comment by MeaningOfLights** [comment]
There's also a dependency on ILogger which I'm suspecting would be a simple fix, but this doesn't work:


            ```
services.AddLogging(config =>
            {
                config.AddDebug();
                config.AddConsole();
                //etc
            });
            
```
Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger

Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate

**Comment by MeaningOfLights** [comment]
I had another play and I can't even get the middleware to work:

`app.UseRequestTimeZone();`

An unhandled exception occurred while processing the request.
InvalidOperationException: No service for type 'Vivet.AspNetCore.RequestTimeZone.RequestTimeZoneMiddleware' has been registered.

If you could provide a barebones sample that would be super useful, thanks.

**Comment by vivet** [comment]
Hi 
I am using the project in this project: https://github.com/Nano-Core/Nano.Library
Here I am probably injecting the ILogger, why it works for me. 

I will take a look, and try to address the issues mentioned.

**Comment by vivet** [comment]
Hi 

I am not sure this: "site: github.com AddRequestTimeZone" should yeild a result. This does "site: github.com RequestTimeZone"

You shouldn't worry about the delegate for ```RequestTimeZoneOptions``` when adding the service. Just do as below
```csharp
services.AddRequestTimeZone(x => 
{
    // Configure options here
}); 
```
You should be able to just look at the readme and follow the instructions, and it should work.

```DateTimeInfo.Local``` was not neccessary, use ```DateTimeInfo.Now```

```ILogger``` dependency has been changed to ```ILoggerFactory```, fixing the depdendency issue. I am using the library in another project where the ILogger was present, so I didn't see the issue. This fixes all depdendency issues you might have had.


Let me know if you are still having issues, or you think the readme is unclear. Then I will fix and improve.

**Comment by MeaningOfLights** [comment]
I really do appreciate you responding so quickly and following up. I've made a Repro to demonstrate the problem with the ILogger reference, I'm not sure it wants ILoggerFactory, its complaining about ILogger and this is a vanilla WebApi project that already wires ILogger up:
https://github.com/MeaningOfLights/RequestTimeZoneDemo

Any insight into how to get it working would be much appreciated, happy to leave the repo public as an example you can reference or fork. Cheers.

**Comment by vivet** [comment]
Hi 
Did you check the branch I made? Everything should be fixed there. 
I tested with a simple webapi application from VS template

**Comment by vivet** [comment]
Your demo project should work with the latest changes in the branch

**Comment by MeaningOfLights** [comment]
Michael, you're a legend!

**Comment by vivet** [comment]
I will deploy updated nuget
