### ISSUE TITLE
System.TimeZoneNotFoundException: The time zone ID 'Asia/Dubai' was not found on the local computer.

### ISSUE THREAD

**Issue by imranbaloch** [vivet/Vivet.AspNetCore#15]
Our logs are full of the below error. Anyway to avoid this error?

```
TimeZone Not Found: Asia/Dubai

Exception: 
System.TimeZoneNotFoundException: The time zone ID 'Asia/Dubai' was not found on the local computer.
   at System.TimeZoneInfo.FindSystemTimeZoneById(String id)
   at Vivet.AspNetCore.RequestTimeZone.RequestTimeZoneMiddleware.InvokeAsync(HttpContext httpContext, RequestDelegate next)

```

**Comment by vivet** [comment]
'Asia/Dubai' is probably not a valid time-zone Id. 
The error is pretty self explanatory, in this: `System.TimeZoneInfo.FindSystemTimeZoneById(String id)
`

**Comment by imranbaloch** [comment]
It is a valid time zone https://nodatime.org/timezones

The problem is that ICU library is not loaded on Windows server and I need to add this library manually.  https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#app-local-icu

**Comment by vivet** [comment]
Will read up on that

**Comment by vivet** [comment]
Have you tried adding this to your application project file?
`<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="<suffix>:<version> or <version>" />
</ItemGroup>`
Or the runtime config explained in the article.

I prefer to leave the library as is, because I don't want to have to mange the update of the ICU version.

**Comment by imranbaloch** [comment]
Yea I fixed it by adding,

```
	<ItemGroup>
		<RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2.0.9"></RuntimeHostConfigurationOption>
		<PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.9" />
    </ItemGroup>
```
