### ISSUE TITLE
README.md example is incorrect

### ISSUE THREAD

**Issue by pfaustinopt** [vivet/Vivet.AspNetCore#16]
While reading the README.md, I've noticed the following:

> Finally, the library also contains a ThreadStatic accessor, called DateTimeInfo.
The implementation exposes the RequestTimezone, as well an utc and local datetime that is based on the timezone.
var now = DateTimeInfo.Now  // Gets datetime
var utc = DateTimeInfo.UtcNow  // Gets utc datetime
var timezone = DateTimeInfo.TimeZone  // Gets the request timezone.

However, `DateTimeInfo.TimeZone` doesn't return a `RequestTimezone` but a `TimeZoneInfo`.  I should also point that to access the timezone information your example should be `DateTimeInfo.TimeZone.Value`, otherwise you'll get `AsyncLocal<TimeZoneInfo>`.

**Comment by vivet** [comment]
I will update the readme
